### ISSUE TITLE
Improve journals export

### ISSUE THREAD

**Issue by Sinled** [MostTornBrain/pf2e-md-exporter#25]
Hi thank you your great addon.

Do you think it would be possible to improve how journals are exported from foundry? For example all beautiful citations and callouts from beginner box premium module are lost during export process and images from such boxed are too big. E.g.

Foundry
<img width="712" alt="Screenshot 2024-10-03 at 18 21 26" src="https://github.com/user-attachments/assets/2beb16fd-d728-4ebd-b763-b0a21081dd35">

Obsidian
<img width="691" alt="Screenshot 2024-10-03 at 18 21 20" src="https://github.com/user-attachments/assets/95015dec-ee9a-446a-94ac-e0d9fcb8d29b">

I can probably fix this with some css selectors magic, but it would be nice to have obsidian callouts or admonition boxes

**Comment by Sinled** [comment]
If anyone stumbles upon this, here are some small css snippets for obsidian that slightly improve exported journals, at least for the Beginner box.

```css
/* Fix pf2e-md-exporter export loosing boxes text layout and increased image size */
.markdown-rendered .markdown-preview-section > div:has(+ div > h2) .image-embed:is([src*="icon-"], [src*="icons/"])  {
    float: left;
    max-width: 100px;
    margin-right: 20px;
}

/* decrease items and inline artwork image size */
.image-embed:is([src*="artwork-items/"], [src*="artwork-other/"])  {
    float: left;
    max-width: 120px;
    margin-right: 20px;
}

/* decrease portraits and mosters image size */
.image-embed:is([src*="portraits-heroes/"], [src*="portraits-bestiary/"])  {
    float: right;
    max-width: 200px;
    margin-left: 20px;
}
```

<img width="915" alt="Screenshot 2024-10-04 at 12 46 46" src="https://github.com/user-attachments/assets/819365a9-cedf-4d73-88e4-1349def58b7e">

<img width="827" alt="Screenshot 2024-10-04 at 12 58 12" src="https://github.com/user-attachments/assets/c3982ad6-fdb2-4d66-b3df-c1158ac37b71">
