### ISSUE TITLE
Monster Core export missing some attack data

### ISSUE THREAD

**Issue by MostTornBrain** [MostTornBrain/pf2e-md-exporter#3]
Looks like the format of how some "held" melee items are stored in the JSON structure is different.  As are result, some attack information is missing from the export.

In Monster Core, The attack information is attached to the object rather than being a separate melee field.  An example is the Goblin Pyro - it has a torch and the melee attack details are attached to the torch.  Compared to Bestiary 1 format, there was an entry for the equipment held (torch) plus a separate entry for the melee attach using the torch.

This might also apply to other forms of equipment.  I'm looking into it now.

**Comment by MostTornBrain** [comment]
Looking at some more monsters, and comparing to the Monster Core pdf, I'm pretty certain this is a Foundry data-entry issue.   For another example, the Gnome Bard in Foundry has no attack data, even if you view the monster in-game world.   Looking at the Monster Core pdf, it has both melee and ranged attack stats listed.

**Comment by wesbaker** [comment]
Hey, I'd love to reopen this and I think I have a hunch at what's going on (and maybe a fix?).

When I open a monster—I'll use a Kobold Warrior for my example—in Foundry I see the following:

<img width="671" alt="Screenshot 2024-11-07 at 1 20 13 PM" src="https://github.com/user-attachments/assets/09280aa3-7f0f-4e68-9431-326bc20f3656">

Note that it has 1 melee and 2 ranged attacks.

When I look at it Obsidian, this is what I see:

<img width="444" alt="Screenshot 2024-11-07 at 1 20 20 PM" src="https://github.com/user-attachments/assets/135b8793-776a-4134-81ce-1e122e1f38de">

You'll see it only has one ranged attack. When you look at the attack block in the YAML, this is what it looks like:

```yml
attacks:
  - name: ""

  - name: "Melee"
    desc: "`pf2:1` Spear +3 ()\n__Damage__  1d6 + 1 piercing"

  - name: "Ranged"
    desc: "`pf2:1` Spear +5 (thrown 20 ft.)\n__Damage__  1d6 + 1 piercing"

  - name: "Ranged"
    desc: "`pf2:1` Sling +5 (propulsive, range increment 50 feet, reload 1)\n__Damage__  1d4 bludgeoning"

  - name: "Scamper"
    desc: "`pf2:1`  **Requirements** The kobold warrior is adjacent to at least one enemy\n* * *\n\n**Effect** The kobold warrior Strides up to their Speed plus 5 feet and gains a +2 circumstance bonus to AC against reactions triggered by this movement. They must end this movement in a space that's not adjacent to any enemy."

  - name: "Sneak Attack"
    desc: "  The kobold warrior deals an extra 1d4 precision damage to off-guard creatures."
```

What's happening (or what I think is happening) is that the latter named YAML blocks are overriding prior ones. So in the above example, we lose out on that first "Ranged" block and only get the second. This problem is more pronounced on dragons who have multiple melee attacks.

A possible solution is to update the [`monster-handlebars.hbs`](https://github.com/MostTornBrain/pf2e-md-exporter/blob/main/handlebars/monster_handlebar.hbs#L77-L80) file:

```diff
{{#each items}}{{#if (eq type "melee")}}
-  - name: "{{#if this.isRanged}}Ranged{{else}}Melee{{/if}}"
-    desc: "`pf2:1` {{this.name}} {{numberFormat system.bonus.value sign=true}} ({{#each system.traits.value}}{{lower (me-trait this)}}{{ifThen @last "" ", "}}{{/each}})\n__Damage__ {{#each system.damageRolls}} {{{this.damage}}} {{this.damageType}}{{#if ../system.attackEffects.value}} plus {{../system.attackEffects.value}}{{/if}}{{/each}}"
+  - name: "{{#if this.isRanged}}Ranged{{else}}Melee{{/if}} {{this.name}}" 
+     desc: "`pf2:1` {{numberFormat system.bonus.value sign=true}} ({{#each system.traits.value}}{{lower (me-trait this)}}{{ifThen @last "" ", "}}{{/each}})\n__Damage__ {{#each system.damageRolls}} {{{this.damage}}} {{this.damageType}}{{#if ../system.attackEffects.value}} plus {{../system.attackEffects.value}}{{/if}}{{/each}}"
{{/if}}{{/each~}}
```

**Comment by wesbaker** [comment]
A short-term fix for the above is to go in and modify the exported content and number the duplicate attacks:

```yml
  - name: "Ranged 1"
    desc: "`pf2:1` Spear +5 (thrown 20 ft.)\n__Damage__  1d6 + 1 piercing"

  - name: "Ranged 2"
    desc: "`pf2:1` Sling +5 (propulsive, range increment 50 feet, reload 1)\n__Damage__  1d4 bludgeoning"
```
