### ISSUE TITLE
Extra name and desc on export - leads to "Map keys must be unique" exceptions

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#7]
I'm seeing many errors of the type:

```
There was an error parsing the Statblock in Character Building/Spells/Warp Step.md: 
Map keys must be unique at line 15, column 5:
    desc: ""
    ^
```

this appears to because name: and desc: attributes with empty strings are sprinkled throughout the exported statblocks.

E.g. here's Character Building/Spells/Warp Step.md

```
```statblock
name: "Warp Step  `pf2:2`"
level: "Cantrip 1"

trait_01: "cantrip"
trait_02: "concentrate"
trait_03: "manipulate"
layout: Basic Pathfinder 2e Layout
columns: 1
columnWidth: x
abilities_top:
  - name: ""
  - name: "Traditions"
    desc: "arcane, occult"

    desc: ""
abilities_mid:
  - name: ""
    desc: "When you walk, the earth warps beneath your feet-your steps extend, distance contracts, and everything is just a little bit closer. You gain a +5-foot status bonus to your Speed until the end of your turn. You then Stride twice. You can use warp step to Burrow, Climb, Fly, or Swim instead of Stride if you have the corresponding movement type.\n\n[[Spell Effects/Spell Effect_ Warp Step|Spell Effect: Warp Step]]"
sourcebook: "_Pathfinder Dark Archive_"
```

I have seen this behavior also on Actor exports. The location of the extra desc in this instance meant that the real desc: was overriden with an empty one. 

I followed the readme recommendations for settings. I do have the checkbox for generating initiative tracker set.
```
