### ISSUE TITLE
All mapping items must start at the same column

### ISSUE THREAD

**Issue by scooper4711** [MostTornBrain/pf2e-md-exporter#8]
I downloaded your fix for issue #7 .
It's significantly better.

However, I'm getting 

```
There was an error parsing the Statblock in Character Building/Spells/Mind Games.md: 

All mapping items must start at the same column at line 15, column 1:

; **Cost** 3 gp game piece focus  - name: "Range"
    desc: "30 feet; **Targets** 1 creature"
^

parse @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
await in parse (async)
add @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
(anonymous) @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146 There was an error parsing the Statblock in Character Building/Spells/Seashell of Stolen Sound.md: 

All mapping items must start at the same column at line 14, column 1:

; **Cost** An unbroken seashell (not consumed)  - name: "Range"
    desc: "30 feet"
^

parse @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
await in parse (async)
add @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
(anonymous) @ 6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146
6c69a29c-b13d-4f7a-8f45-e3bbb8a2fef4:146 There was an error parsing the Statblock in Character Building/Spells/Seize Soul.md: 

All mapping items must start at the same column at line 15, column 1:

; **Cost** item worth at least the target's level x 100 gp  - name: "Range"
    desc: "30 feet; **Targets** 1 creature that died within the last minute"
^
```

e.g. Seashell of Stolen Sound doesn't render at all. Here's the exported md file:

```
---
obsidianUIMode: preview
title: "Seashell of Stolen Sound"
noteType: pf2eSpell
cssclasses: pf2e,pf2e-spell
tags:
  - spell/level/1
  - trait/concentrate
  - trait/sonic
  - trait/common
aliases: "Compendium.pf2e.spells-srd.Item.q5vbYgLztQ04FQZg" 
license: OGL
statblock: inline
---
```statblock
name: "Seashell of Stolen Sound  `pf2:r`"
level: "Spell 1"

trait_01: "concentrate"
trait_02: "sonic"
layout: Basic Pathfinder 2e Layout
columns: 1
columnWidth: x
abilities_top:
  - name: ""
  - name: "Traditions"
    desc: "arcane, occult, primal"
; **Cost** An unbroken seashell (not consumed)  - name: "Range"
    desc: "30 feet"
  - name: "Duration"
    desc: "until your next daily preparations"
abilities_mid:
  - name: ""
    desc: "**Trigger** A creature within range begins to make a sound.\n\nYou store a sound in a seashell to use as you will: the last words of a loved one, a dragon's mighty roar, the compromising conversation between two powerful diplomats, or even more strange and secret. As part of Casting this Spell, you must present an unbroken seashell. When you Cast the Spell, magic swirls around the triggering creature, copying the sounds they make, as well as any background noise, for the next minute and storing them in the seashell.\n\nYou or another creature can then play the sound back from the seashell during the spell's duration by Interacting with the seashell, but once the sounds have been played back, the seashell shatters and the spell ends.\n\nAs normal for spells with a duration until your next daily preparations, you can choose to continue expending the spell slot to prolong the duration of an existing seashell of stolen sound for another day. While the spell faithfully copies the sounds around the target, it doesn't reproduce any special auditory or sonic effects of the sound."
sourcebook: "_Pathfinder Secrets of Magic_"
```

Clearly it's the line with "cost"
